# Generated by Django 2.1.5 on 2019-01-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOB', models.CharField(max_length=3)),
                ('LOBAVG', models.FloatField()),
                ('RATIO', models.FloatField()),
                ('SDEU', models.FloatField()),
                ('AGE', models.FloatField()),
                ('DATE', models.CharField(max_length=50)),
                ('DATETIMESTAMP', models.FloatField()),
                ('LONG', models.FloatField()),
                ('DEVICE_NAME', models.CharField(max_length=10)),
                ('COMPASS', models.FloatField()),
                ('NS', models.IntegerField()),
                ('YAW', models.FloatField()),
                ('PITCH', models.FloatField()),
                ('HEIGHT', models.FloatField()),
                ('Q', models.IntegerField()),
                ('Y', models.FloatField()),
                ('X', models.FloatField()),
                ('Z', models.FloatField()),
                ('SDU', models.FloatField()),
                ('SDNE', models.FloatField()),
                ('SDUN', models.FloatField()),
                ('SDE', models.FloatField()),
                ('TIME', models.CharField(max_length=50)),
                ('LAT', models.FloatField()),
                ('SDN', models.FloatField()),
                ('ROLL', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('LAT', models.FloatField()),
                ('LON', models.FloatField()),
                ('HEIGHT', models.FloatField()),
                ('Power', models.FloatField()),
                ('Freq', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='Sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfvisapp.Sensor'),
        ),
    ]
